###############################################################
#                Authelia minimal configuration               #
###############################################################

port: 9091
tls_cert: /var/lib/authelia/ssl/cert.pem
tls_key: /var/lib/authelia/ssl/key.pem

log_level: debug

jwt_secret: unsecure_secret

authentication_backend:
  file:
    path: /var/lib/authelia/users.yml

session:
  secret: unsecure_session_secret
  domain: example.com
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  remember_me_duration: 1y

storage:
  local:
    path: /var/lib/authelia/db.sqlite

access_control:
  default_policy: bypass
  rules:
    - domain: "public.example.com"
      policy: bypass
    - domain: "admin.example.com"
      policy: two_factor
    - domain: "secure.example.com"
      policy: two_factor
    - domain: "singlefactor.example.com"
      policy: one_factor

notifier:
  smtp:
    host: smtp
    port: 1025
    sender: admin@example.com
    disable_require_tls: true

oidc:
  # This secret must be 32 bytes long
  oauth2_hmac_secret: IVPWBkAdJHje3uz7LtFTDU2pFUfh39Xm
  oidc_issuer_private_key_path: /var/lib/authelia/issuer.pem
  clients:
    client_id: oidc-tester-app
    client_secret: app_secret
    redirect_uris:
      - https://oidc.example.com:8080/oauth2/callback