version: '3'
services:
  authelia-backend:
    volumes:
      - './OIDC/configuration.yml:/etc/authelia/configuration.yml:ro'
      - './OIDC/users.yml:/var/lib/authelia/users.yml'
      - './OIDC/keypair/key.pem:/var/lib/authelia/issuer.pem:ro'
      - './common/ssl:/var/lib/authelia/ssl:ro'